version: '3'

services:
  reverse-proxy:
    image: traefik:v2.2
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /mnt/disk2/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.lookmyhomelab.bid`)"
        - "traefik.http.routers.traefik.entrypoints=https"
        - "traefik.http.routers.traefik.tls=true"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.services.dummy-svc.loadbalancer.server.port=8080"
      placement:
        constraints:
          - node.role == manager

networks:
  traefik-public:
    external: true