blank_issues_enabled: false
contact_links:
  - name: Mon Twitter
    url: https://twitter.com/norfair00
    about: Juste pour me suivre.
  - name: Mon Site
    url: https://norfair00.fr
    about: Mon site personnel.
  - name: Mon Serveur Discord
    url: https://discord.gg/RX7NdEP
    about: Mon serveur discord personnel.
