version: '3'

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - /mnt/disk2/plex/config:/config
      - /mnt/disk1/tv:/tv
      - /mnt/disk1/movies:/movies
      - /mnt/disk1/music:/music
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.plex_https.rule=Host(`plex.lookmyhomelab.bid`)"
        - "traefik.http.routers.plex_https.entrypoints=https"
        - "traefik.http.routers.plex_https.tls=true"
        - "traefik.http.services.plex_https.loadbalancer.server.port=32400"
        - "traefik.docker.network=traefik-public"
      placement:
        constraints:
          - node.role == manager

networks:
  traefik-public:
    external: true